/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "error": "#ba1a1a",
        "secondary-fixed": "#e1e2e4",
        "on-tertiary-container": "#ffede2",
        "on-surface": "#0b1c30",
        "primary": "#4441c4",
        "on-error-container": "#93000a",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-low": "#eff4ff",
        "on-secondary-container": "#606365",
        "on-primary-fixed": "#0b006b",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#a95700",
        "surface-container-high": "#dce9ff",
        "surface-container": "#e5eeff",
        "background": "#f8f9ff",
        "surface-variant": "#d3e4fe",
        "secondary": "#5c5f60",
        "on-primary-fixed-variant": "#3530b6",
        "error-container": "#ffdad6",
        "on-tertiary-fixed": "#301400",
        "primary-container": "#5d5cde",
        "secondary-container": "#dee0e2",
        "inverse-primary": "#c2c1ff",
        "on-secondary-fixed": "#191c1e",
        "on-secondary": "#ffffff",
        "on-primary-container": "#f1eeff",
        "on-surface-variant": "#464554",
        "surface-tint": "#4e4cce",
        "surface-bright": "#f8f9ff",
        "tertiary": "#854300",
        "on-error": "#ffffff",
        "primary-fixed": "#e2dfff",
        "on-secondary-fixed-variant": "#444749",
        "outline": "#777585",
        "on-background": "#0b1c30",
        "tertiary-fixed-dim": "#ffb782",
        "secondary-fixed-dim": "#c5c7c8",
        "primary-fixed-dim": "#c2c1ff",
        "surface-dim": "#cbdbf5",
        "surface-container-highest": "#d3e4fe",
        "inverse-surface": "#213145",
        "surface-container-lowest": "#ffffff",
        "surface": "#f8f9ff",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#703800",
        "tertiary-fixed": "#ffdcc5",
        "outline-variant": "#c7c4d6"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "xs": "4px",
        "xl": "48px",
        "node-gap": "64px",
        "unit": "4px",
        "md": "16px",
        "lg": "24px",
        "sm": "8px"
      },
      "fontFamily": {
        "h1": ["Manrope"],
        "label-caps": ["Inter"],
        "code": ["Inter"],
        "body-lg": ["Inter"],
        "h2": ["Manrope"],
        "body-md": ["Inter"]
      },
      "fontSize": {
        "h1": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "code": ["13px", {"lineHeight": "18px", "fontWeight": "500"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "h2": ["24px", {"lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
